config/routes.rb
Rails.application.routes.draw do

  get 'chat/index'
  get 'chat/new'
  get 'chat/show'

  post '/drink/:id/like', to: 'likes#like_toggle', as:'like_drink'
  resources :comments, only: [:create, :destroy]
  
  get 'place/index'

  get 'recipe/index', to: 'recipe#index'
  
  resources :drink
  
  get '/my_profile', to: 'profiles#show'
  get '/new_profile', to: 'profiles#new'
  post '/create_profile', to: 'profiles#create'
  get '/edit_profile', to: 'profiles#edit'
  patch '/update_profile', to: 'profiles#update'

  root to: 'home#index'
  devise_for :users

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
  belongs_to :post
  belongs_to :drink
end

app/models/drink.rb
class Drink < ActiveRecord::Base
    # TO DO 
    #VALIDATION 
    acts_as_commentable
#이미지업로드모델
    # validates_presence_of :cover
    mount_uploader :cover, CoverUploader
    belongs_to :user
    has_many :likes
    has_many :l_users, through: :likes, source: :user
    
    
    
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :drink
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: {minimum: 1, maximum: 30}
  # VALID_PHONE_NUMBER = /\A010 ([1-9]{1}[0-9]{3}{[0-9]{4}\z/
  # validates :mobile, null: true, format: {with: VALID_PHONE_NUMBER} #Rubular
end 

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile, dependent: :destroy
  
  # redirect_to new_profile_url if sign_in_count == 1
  has_many :comments
  has_many :posts
  has_many :drinks
  has_many :likes
  has_many :l_drinks, through: :likes, source: :drink
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    def index
        @post_all=Chat.all
    end
    def new
    @post = Chat.new
    @token=form_authenticity_token
    end
    def show
    end
    def create
        @post = Chat.new(post_params)
        @post.user = current_user
        @post.save
        if @post.save
            redirect_to '/chat/index'
        else
            render "new"
        end
    end
end

app/controllers/drink_controller.rb
class DrinkController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @post_all = Drink.all
  end
  def show
  end
  def new
    @post = Drink.new
    @token=form_authenticity_token
  end
  def create
    @post = Drink.new(post_params)
    @post.user = current_user
    @post.save
    if @post.save
      redirect_to drink_path(@post)
   else
      render "new"
    end
  end
  def edit
  end
  def update
    @post.user = current_user
    if @post.update(post_params)
     redirect_to drink_path(@post)
    else
      render "edit"
    end
  end
  def destroy
    @post.destroy
    redirect_to '/drink', notice:  "The post #{@post.title} has been deleted."
  end
  # def index
  #   @post_all = Drink.all
  # end
  # def show
  #   @post=Drink.find(params[:id])
  # end
  # def new
  #   #@token=form_authenticity_token
  #   @post = Drink.new
  # end
  # def create
  #   debugger
  #   @post = Drink.new
  #   # @post.title = params[:post_title]
  #   # @post.content = params[:post_content]
  #   # @post.cover = params[:cover]
  #   # @post.save
    
  #   # if @post.save
  #   #     redirect_to "/drink/#{@post.id}", method: "get", notice: "The post #{@post.title} has been uploaded."
  #   #   else
  #   #       redirect_to new_drink_path
  #   # end
  # end
  # def edit
  #   @token=form_authenticity_token
  #   @post = Drink.find(params[:id])
  # end
  # def update
  #   post = Drink.find(params[:id])
  #   post.title = params[:post_title]
  #   post.content = params[:post_content]
  #   post.save
    
  #   redirect_to drink_path
  # end
  # def destroy
  #   @post = Drink.find(params[:id])
  #   @post.destroy
  #   redirect_to '/drink', notice:  "The post #{@post.title} has been deleted."
  # end
  
   private
   def set_post
     @post = Drink.find(params[:id])
   end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:drink).permit(:title, :content, :cover)
    end
    
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    # def create
    #     if Like.find_by(user: current_user, drink_id: params[:id])
    #         Like.create!(user: current_user, drink_id: params[:id])
    #     end
    # end
    # def destroy
    #     unless Like.find_by(user: current_user, drink_id: params[:id])
    #         Like.find_by(user: current_user, drink_id: params[:id]).destroy
    #     end
    # end
    def like_toggle
        like = Like.find_by(user: current_user, drink_id: params[:id])
        if like.nil?
            Like.create!(user: current_user, drink_id: params[:id])
        else
            like.destroy
        end
        redirect_to drink_url(params[:id])
    end
    
end

app/controllers/place_controller.rb
class PlaceController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :new]
  before_action :write_profile, except: [:new, :create]
  
  def new
    @profile = Profile.new
  end
  
  def create
    @profile = current_user.profile
    @profile = Profile.new(profile_params)
    if @profile.save
    # if @profile.save
      redirect_to my_profile_url(@profile)
  else
      render 'new'
    # end
  end

  def show
  end

  def edit
  end
  
  def update
    if @profile.update(profile_params)
      redirect_to my_profile_url(@profile)
    else
      render 'edit'
    end
  end
  
  private
    def set_profile
      @profile = current_user.profile
    end
    def profile_params
      params.permit(:name, :address, :birth, :mobile)
    end
    def write_profile
      redirect_to new_profile_url if current_user.profile.nil?
    end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/chat/index.html.erb
<a href="/chat/new" class="btn btn-primary">NEW CHAT</a>
<br />
<% @post_all.each do |post| %>
    <%=post.id%>
    <a href="/chat/show/<%=post.id%>"><%=post.Title%></a>
<% end %>

app/views/chat/new.html.erb
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    <form action="/chat/create" method="get" >
        <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <input type="text" class="form-control" id="post_title">
        </div>
        <br />
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Content</label>
            <textarea class="form-control" id="post_content" rows="3"></textarea>
        </div>

        <div class="form-group">
            <input type="file" class="form-control-file" id="exampleFormControlFile1">
        </div>

         <a href="/chat/show" class="btn btn-secondary" >Submit</a>
    
 
    </form>

</body>

app/views/chat/show.html.erb
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    제목: 
    <br />
    내용 : 
    <br />
     <a href="/chat/index" class="btn btn-secondary" >BACK</a>
     
</body>

app/views/drink/_form.html.erb
<%= bootstrap_form_for :drink, :url => {:controller => "drink", :action => "create"} do |f| %>

 <div class="form-group">
      <!--<@%= f.label :title, for: "InputTitle1" %><br>-->
      <%= f.text_field :title, class: "form_control" %>
    </div>
    <div class="form-group">
      <!--<@%= @post.cover %>-->
      <!--<@%= f.label :content, for: "exampleTextarea" %><br>-->
      <%= f.text_area :content,  class: "form_control", row: 12%>
    </div>
    <div class="form-group">
        <!--<!%= f.label :cover %>-->
        <%= f.file_field :cover %>
    </div>
    <div class="button_fam">
      <%= f.submit%>
    </div>
 
<% end %>

app/views/drink/_form_update.html.erb
<%= bootstrap_form_for :drink, :url => {:controller => "drink", :action => "update"}, :method => :patch do |f| %>

 <div class="form-group">
      <!--<@%= f.label :title, for: "InputTitle1" %><br>-->
      <%= f.text_field :title, class: "form_control", value: "#{@post.title}" %>
    </div>
    <div class="form-group">
      <!--<@%= @post.cover %>-->
      <!--<@%= f.label :content, for: "exampleTextarea" %><br>-->
      <%= f.text_area :content,  class: "form_control", row: 12, value: "#{@post.content}"%>
    </div>
    <div class="form-group">
        <!--<!%= f.label :cover %>-->
        <%= f.file_field :cover, value: "public/uploads/#{drink}/cover/#{@post.id}/#{@post.cover}" %>
        <!--image_tag("/icons/icon.gif", size: "16")-->
    </div>
    <div class="button_fam">
      <%= f.submit%>
    </div>
 
<% end %>

app/views/drink/edit.html.erb
<%= render 'form_update', drink: @post%>
<!--<h3 style="text-align:center">수정</h3>-->

<!--      <br />-->
<!--<form action="/updateDrink/:id" method="patch">-->
<!--<@%=form_tag(update_path, method:"patch") do %>-->
<!--    <@%= hidden_field_tag :authenticity_token,form_authenticity_token %>-->
<!--    <div class="form-group">-->
<!--      <label for="InputTitle1">TITLE</label>-->
<!--      <input type="text" name="post_title" value="<@%=@post.title%>" class="form-control">-->
<!--    </div>-->

<!--    <div class="form-group">-->
      
<!--   <@%= @post.cover %>-->
 
<!--      <label for="exampleTextarea">CONTENT</label>-->
<!--      <textarea class="form-control"  id="InputContent" name = "post_content" value = "<%=@post.content%>" rows="12">-->
        
<!--<@%=@post.content%>-->
<!--      </textarea>-->
<!--    </div>-->

    <!--<div class="form-group">-->
    <!--  <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp" accept="image/*" name="pic">-->
    <!--</div>-->
<!--    <div class="button_fam">-->
<!--      <p style=text-align:center><input type = "submit" value = "작성완료" class="btn btn-secondary" ></p> -->
<!--    </div>-->
 <!--<p style=text-align:center><a href="/drink/index">작성완료</a></p>-->
<!--<@%end%>-->

app/views/drink/index.html.erb
  <!--<div class="new_article"><a href="/drink/new">새 글 작성</a>-->
  <!--</div>-->
  <!--<br>-->
  <!--<br>-->
  <!-- <div class="title_1"><h1>Posts</h1></div>-->
  <!--<#% #@post_all.each do |p| %>-->
  <!--<a href = "/drink/<#%=p.id%>"><#%=p.title%></a><br/>-->
  <!--<#% end %>-->
  
  <% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New post", new_drink_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>
   <% @post_all.each do |post| %>
      <tr>
         <th>
             <a href = "/my_profile"><%=post.user.email%><br></a>
             </th>
      </tr>
   </thead>
   
   <tbody>
         <tr>
            <td><a href = "/drink/<%=post.id%>"><%=post.title%></a><br/></td>     
         </tr>
      <% end %>
   </tbody>
   
</table>

app/views/drink/new.html.erb
<%= render 'form', drink: @post, :url => {:controller => "drink", :action => "create"} %>

app/views/drink/show.html.erb
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div><h1>Post</h1></div>
    <div class="title_1">
        <label for="InputTitle1">TITLE</label><br/>
        <%=@post.title%>
    </div>
    <div class="title_1">
       
    
        <label for="exempleTextarea">CONTENT</label><br/>
        <!--<@%= @post.cover %><br>-->
        <%= image_tag("#{@post.cover}") %><br>
         
     
        <%=@post.content%>
    </div>
     <a href="/drink" class="btn btn-secondary" >BACK</a>
     <a href="/drink/<%=@post.id%>/edit" class="btn btn-secondary" >EDIT</a>
     <%= button_to "Delete", "/drink/#{@post.id}", method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{@post.title}?" %></td>
    
    
    <!--좋아요-->
    <% if @post.l_users.include?(current_user) %>
    <!--    좋아요를 했다면 --!>-->
        <%= link_to like_drink_path, method: :post do  %>
            <span style="color:red"><%= fa_icon "heart" %></span>
        <% end %>
    <% else %>
    <!--     좋아요를 안했다면 --!>-->
        <%= link_to like_drink_path, method: :post do  %>
            <span style="color:black"><%= fa_icon "heart" %></span>
        <% end %>
    <% end %>
    <strong>
        <%= @post.likes.count %>명이 좋아합니다.
    </strong>
    
    
    <!--댓글 뷰 -->
    <% @post.comments.each do |comment| %>
    <div class="card">
      <h5 class="card-header">
          <%=comment.user.email %></h5>
      <div class="card-body">
        <p class="card-text">
            <%=comment.comment %>
        </p>
      </div>
    </div>
    <% end %>
    
    <%= bootstrap_form_for Comment.new do |f| %>
    <%= f.hidden_field :commentable_id, value: @post.id %>
    <%= f.hidden_field :commentable_type, value: @post.class%>
    <%= f.text_field :comment%>
    <%= f.submit %>
    <%end%>
</body>

app/views/recipe/index.html.erb
  <% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New post", new_recipe_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>
   <% @post_all.each do |post| %>
      <tr>
         <th><a href = "/my_profile"><%=post.user.email%></a><br></th>
      </tr>
   </thead>
   
   <tbody>
         <tr>
            <td><a href = "/recipe/<%=post.id%>"><%=post.title%></a><br/></td>     
         </tr>
         
      <% end %>
   </tbody>
   
</table>