config/routes.rb
Rails.application.routes.draw do

  get 'chat/index'
  get 'chat/new'
  get 'chat/show'

  post '/drink/:id/like', to: 'likes#like_toggle', as:'like_drink'
  resources :comments, only: [:create, :destroy]
  
  get 'place/index'

  get 'recipe/index', to: 'recipe#index'
  
  resources :drink
  
  get '/my_profile', to: 'profiles#show'
  get '/new_profile', to: 'profiles#new'
  post '/create_profile', to: 'profiles#create'
  get '/edit_profile', to: 'profiles#edit'
  patch '/update_profile', to: 'profiles#update'

  root to: 'home#index'
  devise_for :users

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
  belongs_to :post
  belongs_to :drink
end

app/models/drink.rb
class Drink < ActiveRecord::Base
    # TO DO 
    #VALIDATION 
    acts_as_commentable
#이미지업로드모델
    # validates_presence_of :cover
    mount_uploader :cover, CoverUploader
    belongs_to :user
    has_many :likes
    has_many :l_users, through: :likes, source: :user
    
    
    
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :drink
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: {minimum: 1, maximum: 30}
  # VALID_PHONE_NUMBER = /\A010 ([1-9]{1}[0-9]{3}{[0-9]{4}\z/
  # validates :mobile, null: true, format: {with: VALID_PHONE_NUMBER} #Rubular
end 

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile, dependent: :destroy
  
  # redirect_to new_profile_url if sign_in_count == 1
  has_many :comments
  has_many :posts
  has_many :drinks
  has_many :likes
  has_many :l_drinks, through: :likes, source: :drink
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    def index
        @post_all=Chat.all
    end
    def new
    @post = Chat.new
    @token=form_authenticity_token
    end
    def show
    end
    def create
        @post = Chat.new(post_params)
        @post.user = current_user
        @post.save
        if @post.save
            redirect_to '/chat/index'
        else
            render "new"
        end
    end
end

app/controllers/drink_controller.rb
class DrinkController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @post_all = Drink.all
  end
  def show
  end
  def new
    @post = Drink.new
    @token=form_authenticity_token
  end
  def create
    @post = Drink.new(post_params)
    @post.user = current_user
    @post.save
    if @post.save
      redirect_to drink_path(@post)
   else
      render "new"
    end
  end
  def edit
  end
  def update
    @post.user = current_user
    if @post.update(post_params)
     redirect_to drink_path(@post)
    else
      render "edit"
    end
  end
  def destroy
    @post.destroy
    redirect_to '/drink', notice:  "The post #{@post.title} has been deleted."
  end
  # def index
  #   @post_all = Drink.all
  # end
  # def show
  #   @post=Drink.find(params[:id])
  # end
  # def new
  #   #@token=form_authenticity_token
  #   @post = Drink.new
  # end
  # def create
  #   debugger
  #   @post = Drink.new
  #   # @post.title = params[:post_title]
  #   # @post.content = params[:post_content]
  #   # @post.cover = params[:cover]
  #   # @post.save
    
  #   # if @post.save
  #   #     redirect_to "/drink/#{@post.id}", method: "get", notice: "The post #{@post.title} has been uploaded."
  #   #   else
  #   #       redirect_to new_drink_path
  #   # end
  # end
  # def edit
  #   @token=form_authenticity_token
  #   @post = Drink.find(params[:id])
  # end
  # def update
  #   post = Drink.find(params[:id])
  #   post.title = params[:post_title]
  #   post.content = params[:post_content]
  #   post.save
    
  #   redirect_to drink_path
  # end
  # def destroy
  #   @post = Drink.find(params[:id])
  #   @post.destroy
  #   redirect_to '/drink', notice:  "The post #{@post.title} has been deleted."
  # end
  
   private
   def set_post
     @post = Drink.find(params[:id])
   end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:drink).permit(:title, :content, :cover)
    end
    
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    # def create
    #     if Like.find_by(user: current_user, drink_id: params[:id])
    #         Like.create!(user: current_user, drink_id: params[:id])
    #     end
    # end
    # def destroy
    #     unless Like.find_by(user: current_user, drink_id: params[:id])
    #         Like.find_by(user: current_user, drink_id: params[:id]).destroy
    #     end
    # end
    def like_toggle
        like = Like.find_by(user: current_user, drink_id: params[:id])
        if like.nil?
            Like.create!(user: current_user, drink_id: params[:id])
        else
            like.destroy
        end
        redirect_to drink_url(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/layouts/_footer.html.erb
<footer class="container">
    <hr>
    <br />
    <br />
    <small>
        @made by home_sul team
    </small>
    <br />
</footer>

app/views/layouts/_header.html.erb
<header>
<% if user_signed_in? %>
  <!--이름으로 바꾸기-->
    <p style="text-align:right;"><%= current_user.email %>님 환영합니다.<%=link_to 'sign out', destroy_user_session_path, method: 'delete' %> <%=link_to 'My Profile', my_profile_path, method: 'get' %>  </p>
<% else %>
  <p style="text-align:right;">로그인하세요.  <a href="/users/sign_in">sign in</a></p>
<% end %>
<center><%= link_to "HOME술", root_path, id:'logo', class: 'navbar-brand' %></center>
<ul class="nav justify-content-center" id="menu">
  <li class="nav-item">
    <a class="nav-link" href="/drink">술</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href='/recipe/index'>레시피</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href='/place/index'>술집</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">커뮤니티</a></a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href='#'>WEBZIN</a>
      <a class="dropdown-item" href='#'>EVENT</a>
      <a class="dropdown-item" href='/chat/index'>CHAT</a>
    </div>
  </li>
</ul>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
    <!--fa_icon주소-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render '/layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="container">
    <%= yield %>
  </div>
  <%= render '/layouts/footer' %>
  <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
  <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>-->
  <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->
</body>
</html>